name: cah-lobby
version: '1.0'
main: github.dimazbtw.lobby.Main
authors: [ dimaz ]

#TODO
#ALTERAR OS SLOTS DOS ITENS, ESPADA 0 E GAME 4
#SISTEMA DE PVP
#ARRUMAR OS COMANDOS DOS ARMORSTANDS
#PODER ADICIONAR MAIS PARTICULAS
#ARRUMAR O HEIGHT DAS PARTICULAS
#MENUS DE MODOS DE JOGO, PERFIL E LOBBIES
#TOP DE PVP
#PREFERENCIAS: CHAT, TELL, FLY, LANG
#PERFIL: PREFERENCIAS, SOCIAIS, ESTATISTICAS